[supabase]
url = "https://nxyiwtgdajyeyhpqkwig.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im54eWl3dGdkYWp5ZXlocHFrd2lnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMzNzM5NDYsImV4cCI6MjA3ODk0OTk0Nn0.pPl9bnGw5utQx4BISAKt3FxazfEJcPd3FCgR49ZnJUM"