[supabase]
url = "https://nxyiwtgdajyeyhpqkwig.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im54eWl3dGdkYWp5ZXlocHFrd2lnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMzNzM5NDYsImV4cCI6MjA3ODk0OTk0Nn0.pPl9bnGw5utQx4BISAKt3FxazfEJcPd3FCgR49ZnJUM"

[supabase_admin]
service_role_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im54eWl3dGdkYWp5ZXlocHFrd2lnIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MzM3Mzk0NiwiZXhwIjoyMDc4OTQ5OTQ2fQ.TuHX-uYfRR6_RunzAJ1rEDDSDSDRuvfr-Dc4c31nS_4"